name: Parse and Update Playlists

on:
  schedule:
    # Esegue ogni 12 ore alle 03:00 e 15:00 UTC (04:00/16:00 in Italia)
    - cron: '0 3,15 * * *'
  workflow_dispatch: # Permette di far partire l'azione manualmente da GitHub

permissions:
  contents: write

jobs:
  update-m3u-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Parser Script
        run: python parser.py
        env:
          M3U_LIVE_URL: ${{ secrets.M3U_LIVE_URL }}
          M3U_FILM_URL: ${{ secrets.M3U_FILM_URL }}
          M3U_SERIES_URL: ${{ secrets.M3U_SERIES_URL }}
          EPG_URL: ${{ secrets.EPG_URL }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # Commit solo se ci sono cambiamenti
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update: Aggiornamento Liste e EPG - ${{ github.run_number }}"
          git pull --rebase origin main
          git push origin main
